### ISSUE TITLE
Opera in iOS

### ISSUE THREAD

**Issue by MarkyMarkNo1** [antivanov/sniffr#3]
Hi Anton,

for Opera in iOS, Sniffr.browser.name returns 'UNKNOWN', as navigator.userAgent does not contain /opera/.

Since for Opera in iOS we have to expect a UA-String like 

![office lens_20160209_182051_processed](https://cloud.githubusercontent.com/assets/2435073/12924610/3a8e5e1c-cf5b-11e5-8d41-7ab5f37287d8.jpg)

something like 

`navigator.userAgent.match( /OPiOS/i )`

will work.

Thank you!

**Comment by antivanov** [comment]
Hi,

Thank you for reporting the issue. I will add support for this case and publish an updated package.

**Comment by MarkyMarkNo1** [comment]
Thank you for your efforts!

**Comment by antivanov** [comment]
The package has been updated and should be available in the Bower repository and NPM. Thanks for providing the user agent string, it was included into the test suite

**Comment by MarkyMarkNo1** [comment]
Thanks Anton, but the regex doesn't seem to work?

For the provided UA-String, Sniffr.browser.name still returns 'UNKNOWN'?

**Comment by antivanov** [comment]
Hi Mark,

The user agent string in the screenshot is recognized, here is a small code snippet to test it against the latest package published to NPM https://tonicdev.com/56ba4f7d9c9a4c0d00f61855/56bb9e41d5fc4b0d00ae9cb7

Have you updated the package version? Is another Opera user agent string not properly recognized?
Please, also note that on the screenshot the user agent string includes the browser version: `OPiOS/12.1.1.98980`

**Comment by MarkyMarkNo1** [comment]
Maybe the fault's on my side. I'll get back here in case of new findings. Thank you.
